---
title: "Vis_Fetal_Loss"
author: "Evgeniia Molokova"
date: "2023-01-26"
output: html_document
---
# Загрузка библиотек и настройка кода
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library (dplyr)
library (tibble)
library (stringr)
library (readr)
library (readxl)
```

# Формирование общего датасета, объединяющего исходный датасет и все методы импутации
```{r}
library(ggpubr)
library (rstatix)


#Загрузка датасетов: исходного и по различным методам импутации

df1 <- read_csv("df1_csv.csv")
df1 <-df1 %>%
  select(!`СЗРП`)

df1_na <- read_csv("df1_na_csv.csv")
df1_na <- df1_na %>%
  select(!`СЗРП`)

df1_process_mean <- read_csv("df1_process_mean.csv")
df1_process_mean <-  df1_process_mean %>%
  select(!`СЗРП`)

df1_process_median<- read_csv("df1_process_median.csv")
df1_process_median <- df1_process_median %>%
  select(!`СЗРП`)

df1_process_mode <- read_csv("df1_process_mode.csv")
df1_process_mode <- df1_process_mode %>%
  select(!`СЗРП`)

df1_knn5 <- read_xlsx("df1_knn5.xlsx")
df1_knn5 <-  df1_knn5 %>%
  select(!`СЗРП` & !`impute_type`)

df1_MICE <-  read_csv("MICE_imputation.csv")


#Создание итогового датасета для визуализации
lst <- list(df1, df1_na, df1_process_mean, df1_process_median, df1_process_mode, df1_knn5, df1_MICE )
lst <- lapply(1:length(lst), function(x){
  lst[[x]] <- lst[[x]] %>%
    mutate(name = paste("DF",x))
})

whole <- do.call(rbind, lst)
whole$name <- as.factor(whole$name)
```


# Визуализация переменных и соответствующих сроков гестации, в которых были выявлены статистически значимые различия по тесту Фридмана
```{r}
whole %>%
  filter(Гестация == 21) %>%
ggviolin (x = "name", y = "Почки", fill = "name", palette = c("#CCFF99", "#FF99CC", "#CCCCFF", "#FFCC66", "#CC99FF", "#FFFF00", "#FF0000", "#FFCCCC"), alpha=0.5, size=0.1,  add = "boxplot", add.params = list(fill = "white", size=0.2, width = 0.1, alpha=0.5))+
  theme_light()+
  xlab("Датафрейм")+
  ylab("Почки, г")+
  ggtitle("Гестация - 21 неделя", )+
  theme(plot.title = element_text(hjust = 0.5 ))+
  theme(axis.title.y = element_text (size=12, margin = margin(l = 10, r = 10)))+
  theme(axis.title.x = element_text (size=12, margin = margin(t = 10, b = 10)))+
  theme(axis.text.x = element_text(size=10, ))+
  theme(legend.position = "none")+
  scale_x_discrete(labels=c('Исходный', 'Удаление
  пропусков', 'Замена NA
  на среднее', 'Замена NA
  на медиану','Замена NA
  на моду', 'knn5', 'MICE'))+
  scale_y_continuous (breaks = c (0,2,4,6,8,10,12,14,16), limits = c(0, 15))
```


```{r}
whole %>%
  filter(Гестация == 21) %>%
ggviolin (x = "name", y = "Тимус", fill = "name", palette = c("#CCFF99", "#FF99CC", "#CCCCFF", "#FFCC66", "#CC99FF", "#FFFF00", "#FF0000", "#FFCCCC"), alpha=0.5, size=0.1, width = 0.9,  add = "boxplot", add.params = list(fill = "white", size=0.2, width = 0.1, alpha=0.5))+
  theme_light()+
  xlab("Датафрейм")+
  ylab("Тимус, г")+
  ggtitle("Гестация - 21 неделя", )+
  theme(plot.title = element_text(hjust = 0.5 ))+
  theme(axis.title.y = element_text (size=12, margin = margin(l = 10, r = 10)))+
  theme(axis.title.x = element_text (size=12, margin = margin(t = 10, b = 10)))+
  theme(axis.text.x = element_text(size=10, ))+
  theme(legend.position = "none")+
  scale_x_discrete(labels=c('Исходный', 'Удаление
  пропусков', 'Замена NA
  на среднее', 'Замена NA
  на медиану','Замена NA
  на моду', 'knn5', 'MICE'))+
  scale_y_continuous (breaks = c (0,0.5,1, 1.5, 2,2.5,3,3.5,4,4.5), limits = c(0, 4))
```
```{r}
whole %>%
  filter(Гестация == 22) %>%
ggviolin (x = "name", y = "Надпочечники", fill = "name", palette = c("#CCFF99", "#FF99CC", "#CCCCFF", "#FFCC66", "#CC99FF", "#FFFF00", "#FF0000", "#FFCCCC"), alpha=0.5, size=0.1, width = 0.9,  add = "boxplot", add.params = list(fill = "white", size=0.2, width = 0.1, alpha=0.5))+
  theme_light()+
  xlab("Датафрейм")+
  ylab("Надпочечники, г")+
  ggtitle("Гестация - 22 неделя", )+
  theme(plot.title = element_text(hjust = 0.5 ))+
  theme(axis.title.y = element_text (size=12, margin = margin(l = 10, r = 10)))+
  theme(axis.title.x = element_text (size=12, margin = margin(t = 10, b = 10)))+
  theme(axis.text.x = element_text(size=10, ))+
  theme(legend.position = "none")+
  scale_x_discrete(labels=c('Исходный', 'Удаление
  пропусков', 'Замена NA
  на среднее', 'Замена NA
  на медиану','Замена NA
  на моду', 'knn5', 'MICE'))+
  scale_y_continuous (breaks = c (0,0.5,1, 1.5, 2,2.5,3,3.5,4,4.5), limits = c(0, 4.25))
```
```{r}
whole %>%
  filter(Гестация == 22) %>%
ggviolin (x = "name", y = "Поджелудочная железа", fill = "name", palette = c("#CCFF99", "#FF99CC", "#CCCCFF", "#FFCC66", "#CC99FF", "#FFFF00", "#FF0000", "#FFCCCC"), alpha=0.5, size=0.1, width = 1,  add = "boxplot", add.params = list(fill = "white", size=0.2, width = 0.1, alpha=0.5))+
  theme_light()+
  xlab("Датафрейм")+
  ylab("Поджелудочная железа, г")+
  ggtitle("Гестация - 22 неделя", )+
  theme(plot.title = element_text(hjust = 0.5 ))+
  theme(axis.title.y = element_text (size=12, margin = margin(l = 10, r = 10)))+
  theme(axis.title.x = element_text (size=12, margin = margin(t = 10, b = 10)))+
  theme(axis.text.x = element_text(size=10, ))+
  theme(legend.position = "none")+
  scale_x_discrete(labels=c('Исходный', 'Удаление
  пропусков', 'Замена NA
  на среднее', 'Замена NA
  на медиану','Замена NA
  на моду', 'knn5', 'MICE'))+
  scale_y_continuous (breaks = c (0,0.25,0.5,0.75,1,1.25,1.5,1.75,2,2.25,2.5,2.75,3), limits = c(0, 2.75))
```
```{r}
whole %>%
  filter(Гестация == 22) %>%
ggviolin (x = "name", y = "Почки", fill = "name", palette = c("#CCFF99", "#FF99CC", "#CCCCFF", "#FFCC66", "#CC99FF", "#FFFF00", "#FF0000", "#FFCCCC"), alpha=0.5, size=0.1, width = 0.9,  add = "boxplot", add.params = list(fill = "white", size=0.2, width = 0.1, alpha=0.5))+
  theme_light()+
  xlab("Датафрейм")+
  ylab("Почки, г")+
  ggtitle("Гестация - 22 неделя", )+
  theme(plot.title = element_text(hjust = 0.5 ))+
  theme(axis.title.y = element_text (size=12, margin = margin(l = 10, r = 10)))+
  theme(axis.title.x = element_text (size=12, margin = margin(t = 10, b = 10)))+
  theme(axis.text.x = element_text(size=10, ))+
  theme(legend.position = "none")+
  scale_x_discrete(labels=c('Исходный', 'Удаление
  пропусков', 'Замена NA
  на среднее', 'Замена NA
  на медиану','Замена NA
  на моду', 'knn5', 'MICE'))+
  scale_y_continuous (breaks = c (0,2,4,6,8,10,12,14,16), limits = c(0, 15))
```
```{r}
whole %>%
  filter(Гестация == 22) %>%
ggviolin (x = "name", y = "Селезёнка", fill = "name", palette = c("#CCFF99", "#FF99CC", "#CCCCFF", "#FFCC66", "#CC99FF", "#FFFF00", "#FF0000", "#FFCCCC"), alpha=0.5, size=0.1, width = 0.9,  add = "boxplot", add.params = list(fill = "white", size=0.2, width = 0.1, alpha=0.5))+
  theme_light()+
  xlab("Датафрейм")+
  ylab("Селезёнка, г")+
  ggtitle("Гестация - 22 неделя", )+
  theme(plot.title = element_text(hjust = 0.5 ))+
  theme(axis.title.y = element_text (size=12, margin = margin(l = 10, r = 10)))+
  theme(axis.title.x = element_text (size=12, margin = margin(t = 10, b = 10)))+
  theme(axis.text.x = element_text(size=10, ))+
  theme(legend.position = "none")+
  scale_x_discrete(labels=c('Исходный', 'Удаление
  пропусков', 'Замена NA
  на среднее', 'Замена NA
  на медиану','Замена NA
  на моду', 'knn5', 'MICE'))+
  scale_y_continuous (breaks = c (0,0.5,1, 1.5, 2,2.5,3,3.5,4,4.5), limits = c(0, 4.5))
```
```{r}
whole %>%
  filter(Гестация == 22) %>%
ggviolin (x = "name", y = "Сердце", fill = "name", palette = c("#CCFF99", "#FF99CC", "#CCCCFF", "#FFCC66", "#CC99FF", "#FFFF00", "#FF0000", "#FFCCCC"), alpha=0.5, size=0.1, width = 0.9,  add = "boxplot", add.params = list(fill = "white", size=0.2, width = 0.1, alpha=0.5))+
  theme_light()+
  xlab("Датафрейм")+
  ylab("Сердце, г")+
  ggtitle("Гестация - 22 неделя", )+
  theme(plot.title = element_text(hjust = 0.5 ))+
  theme(axis.title.y = element_text (size=12, margin = margin(l = 10, r = 10)))+
  theme(axis.title.x = element_text (size=12, margin = margin(t = 10, b = 10)))+
  theme(axis.text.x = element_text(size=10, ))+
  theme(legend.position = "none")+
  scale_x_discrete(labels=c('Исходный', 'Удаление
  пропусков', 'Замена NA
  на среднее', 'Замена NA
  на медиану','Замена NA
  на моду', 'knn5', 'MICE'))+
  scale_y_continuous (breaks = c (0,1,2,3,4,5,6,7,8,9,10), limits = c(0, 10))
```
```{r}
whole %>%
  filter(Гестация == 23) %>%
ggviolin (x = "name", y = "Лёгкие", fill = "name", palette = c("#CCFF99", "#FF99CC", "#CCCCFF", "#FFCC66", "#CC99FF", "#FFFF00", "#FF0000", "#FFCCCC"), alpha=0.5, size=0.1, width = 0.9,  add = "boxplot", add.params = list(fill = "white", size=0.2, width = 0.1, alpha=0.5))+
  theme_light()+
  xlab("Датафрейм")+
  ylab("Лёгкие, г")+
  ggtitle("Гестация - 23 неделя", )+
  theme(plot.title = element_text(hjust = 0.5 ))+
  theme(axis.title.y = element_text (size=12, margin = margin(l = 10, r = 10)))+
  theme(axis.title.x = element_text (size=12, margin = margin(t = 10, b = 10)))+
  theme(axis.text.x = element_text(size=10, ))+
  theme(legend.position = "none")+
  scale_x_discrete(labels=c('Исходный', 'Удаление
  пропусков', 'Замена NA
  на среднее', 'Замена NA
  на медиану','Замена NA
  на моду', 'knn5', 'MICE'))+
  scale_y_continuous (breaks = c (0,5,10,15,20,25,30,35,40), limits = c(0, 40))
```
```{r}
whole %>%
  filter(Гестация == 23) %>%
ggviolin (x = "name", y = "Печень", fill = "name", palette = c("#CCFF99", "#FF99CC", "#CCCCFF", "#FFCC66", "#CC99FF", "#FFFF00", "#FF0000", "#FFCCCC"), alpha=0.5, size=0.1, width = 0.9,  add = "boxplot", add.params = list(fill = "white", size=0.2, width = 0.1, alpha=0.5))+
  theme_light()+
  xlab("Датафрейм")+
  ylab("Печень, г")+
  ggtitle("Гестация - 23 неделя", )+
  theme(plot.title = element_text(hjust = 0.5 ))+
  theme(axis.title.y = element_text (size=12, margin = margin(l = 10, r = 10)))+
  theme(axis.title.x = element_text (size=12, margin = margin(t = 10, b = 10)))+
  theme(axis.text.x = element_text(size=10, ))+
  theme(legend.position = "none")+
  scale_x_discrete(labels=c('Исходный', 'Удаление
  пропусков', 'Замена NA
  на среднее', 'Замена NA
  на медиану','Замена NA
  на моду', 'knn5', 'MICE'))+
  scale_y_continuous (breaks = c (0,5,10,15,20,25,30,35,40,45,50,55,60,65,70), limits = c(0, 70))
```
```{r}
whole %>%
  filter(Гестация == 23) %>%
ggviolin (x = "name", y = "Поджелудочная железа", fill = "name", palette = c("#CCFF99", "#FF99CC", "#CCCCFF", "#FFCC66", "#CC99FF", "#FFFF00", "#FF0000", "#FFCCCC"), alpha=0.5, size=0.1, width = 1.5,  add = "boxplot", add.params = list(fill = "white", size=0.2, width = 0.1, alpha=0.5))+
  theme_light()+
  xlab("Датафрейм")+
  ylab("Поджелудочная железа, г")+
  ggtitle("Гестация - 23 неделя", )+
  theme(plot.title = element_text(hjust = 0.5 ))+
  theme(axis.title.y = element_text (size=12, margin = margin(l = 10, r = 10)))+
  theme(axis.title.x = element_text (size=12, margin = margin(t = 10, b = 10)))+
  theme(axis.text.x = element_text(size=10, ))+
  theme(legend.position = "none")+
  scale_x_discrete(labels=c('Исходный', 'Удаление
  пропусков', 'Замена NA
  на среднее', 'Замена NA
  на медиану','Замена NA
  на моду', 'knn5', 'MICE'))+
  scale_y_continuous (breaks = c (0,0.25,0.5,0.75,1,1.25,1.5,1.75,2,2.25), limits = c(0, 2.25))
```
```{r}
whole %>%
  filter(Гестация == 23) %>%
ggviolin (x = "name", y = "Селезёнка", fill = "name", palette = c("#CCFF99", "#FF99CC", "#CCCCFF", "#FFCC66", "#CC99FF", "#FFFF00", "#FF0000", "#FFCCCC"), alpha=0.5, size=0.1, width = 0.9,  add = "boxplot", add.params = list(fill = "white", size=0.2, width = 0.1, alpha=0.5))+
  theme_light()+
  xlab("Датафрейм")+
  ylab("Селезёнка, г")+
  ggtitle("Гестация - 23 неделя", )+
  theme(plot.title = element_text(hjust = 0.5 ))+
  theme(axis.title.y = element_text (size=12, margin = margin(l = 10, r = 10)))+
  theme(axis.title.x = element_text (size=12, margin = margin(t = 10, b = 10)))+
  theme(axis.text.x = element_text(size=10, ))+
  theme(legend.position = "none")+
  scale_x_discrete(labels=c('Исходный', 'Удаление
  пропусков', 'Замена NA
  на среднее', 'Замена NA
  на медиану','Замена NA
  на моду', 'knn5', 'MICE'))+
  scale_y_continuous (breaks = c (0,0.5,1, 1.5, 2,2.5,3,3.5,4,4.5), limits = c(0, 4.5))
```
```{r}
whole %>%
  filter(Гестация == 23) %>%
ggviolin (x = "name", y = "Сердце", fill = "name", palette = c("#CCFF99", "#FF99CC", "#CCCCFF", "#FFCC66", "#CC99FF", "#FFFF00", "#FF0000", "#FFCCCC"), alpha=0.5, size=0.1, width = 0.9,  add = "boxplot", add.params = list(fill = "white", size=0.2, width = 0.1, alpha=0.5))+
  theme_light()+
  xlab("Датафрейм")+
  ylab("Сердце, г")+
  ggtitle("Гестация - 23 неделя", )+
  theme(plot.title = element_text(hjust = 0.5 ))+
  theme(axis.title.y = element_text (size=12, margin = margin(l = 10, r = 10)))+
  theme(axis.title.x = element_text (size=12, margin = margin(t = 10, b = 10)))+
  theme(axis.text.x = element_text(size=10, ))+
  theme(legend.position = "none")+
  scale_x_discrete(labels=c('Исходный', 'Удаление
  пропусков', 'Замена NA
  на среднее', 'Замена NA
  на медиану','Замена NA
  на моду', 'knn5', 'MICE'))+
  scale_y_continuous (breaks = c (0,1,2,3,4,5,6,7,8,9,10), limits = c(0, 9))
```
```{r}
whole %>%
  filter(Гестация == 24) %>%
ggviolin (x = "name", y = "Лёгкие", fill = "name", palette = c("#CCFF99", "#FF99CC", "#CCCCFF", "#FFCC66", "#CC99FF", "#FFFF00", "#FF0000", "#FFCCCC"), alpha=0.5, size=0.1, width = 0.9,  add = "boxplot", add.params = list(fill = "white", size=0.2, width = 0.1, alpha=0.5))+
  theme_light()+
  xlab("Датафрейм")+
  ylab("Лёгкие, г")+
  ggtitle("Гестация - 24 неделя", )+
  theme(plot.title = element_text(hjust = 0.5 ))+
  theme(axis.title.y = element_text (size=12, margin = margin(l = 10, r = 10)))+
  theme(axis.title.x = element_text (size=12, margin = margin(t = 10, b = 10)))+
  theme(axis.text.x = element_text(size=10, ))+
  theme(legend.position = "none")+
  scale_x_discrete(labels=c('Исходный', 'Удаление
  пропусков', 'Замена NA
  на среднее', 'Замена NA
  на медиану','Замена NA
  на моду', 'knn5', 'MICE'))+
  scale_y_continuous (breaks = c (0,5,10,15,20,25,30,35,40), limits = c(0, 40))
```

```{r}
whole %>%
  filter(Гестация == 24) %>%
ggviolin (x = "name", y = "Плацента", fill = "name", palette = c("#CCFF99", "#FF99CC", "#CCCCFF", "#FFCC66", "#CC99FF", "#FFFF00", "#FF0000", "#FFCCCC"), alpha=0.5, size=0.1, width = 0.9,  add = "boxplot", add.params = list(fill = "white", size=0.2, width = 0.1, alpha=0.5))+
  theme_light()+
  xlab("Датафрейм")+
  ylab("Плацента, г")+
  ggtitle("Гестация - 24 неделя", )+
  theme(plot.title = element_text(hjust = 0.5 ))+
  theme(axis.title.y = element_text (size=12, margin = margin(l = 10, r = 10)))+
  theme(axis.title.x = element_text (size=12, margin = margin(t = 10, b = 10)))+
  theme(axis.text.x = element_text(size=10, ))+
  theme(legend.position = "none")+
  scale_x_discrete(labels=c('Исходный', 'Удаление
  пропусков', 'Замена NA
  на среднее', 'Замена NA
  на медиану','Замена NA
  на моду', 'knn5', 'MICE'))+
  scale_y_continuous (breaks = c (0,50,100,150,200,250,300,350,400, 450,500), limits = c(0, 500))
```

```{r}
whole %>%
  filter(Гестация == 24) %>%
ggviolin (x = "name", y = "Поджелудочная железа", fill = "name", palette = c("#CCFF99", "#FF99CC", "#CCCCFF", "#FFCC66", "#CC99FF", "#FFFF00", "#FF0000", "#FFCCCC"), alpha=0.5, size=0.1, width = 1.5,  add = "boxplot", add.params = list(fill = "white", size=0.2, width = 0.1, alpha=0.5))+
  theme_light()+
  xlab("Датафрейм")+
  ylab("Поджелудочная железа, г")+
  ggtitle("Гестация - 24 неделя", )+
  theme(plot.title = element_text(hjust = 0.5 ))+
  theme(axis.title.y = element_text (size=12, margin = margin(l = 10, r = 10)))+
  theme(axis.title.x = element_text (size=12, margin = margin(t = 10, b = 10)))+
  theme(axis.text.x = element_text(size=10, ))+
  theme(legend.position = "none")+
  scale_x_discrete(labels=c('Исходный', 'Удаление
  пропусков', 'Замена NA
  на среднее', 'Замена NA
  на медиану','Замена NA
  на моду', 'knn5', 'MICE'))+
  scale_y_continuous (breaks = c (0,0.25,0.5,0.75,1,1.25,1.5,1.75,2,2.25, 2.5), limits = c(0, 2.5))
```
```{r}
whole %>%
  filter(Гестация == 24) %>%
ggviolin (x = "name", y = "Селезёнка", fill = "name", palette = c("#CCFF99", "#FF99CC", "#CCCCFF", "#FFCC66", "#CC99FF", "#FFFF00", "#FF0000", "#FFCCCC"), alpha=0.5, size=0.1, width = 0.9,  add = "boxplot", add.params = list(fill = "white", size=0.2, width = 0.1, alpha=0.5))+
  theme_light()+
  xlab("Датафрейм")+
  ylab("Селезёнка, г")+
  ggtitle("Гестация - 24 неделя", )+
  theme(plot.title = element_text(hjust = 0.5 ))+
  theme(axis.title.y = element_text (size=12, margin = margin(l = 10, r = 10)))+
  theme(axis.title.x = element_text (size=12, margin = margin(t = 10, b = 10)))+
  theme(axis.text.x = element_text(size=10, ))+
  theme(legend.position = "none")+
  scale_x_discrete(labels=c('Исходный', 'Удаление
  пропусков', 'Замена NA
  на среднее', 'Замена NA
  на медиану','Замена NA
  на моду', 'knn5', 'MICE'))+
  scale_y_continuous (breaks = c (0,0.5,1, 1.5, 2,2.5,3,3.5,4,4.5), limits = c(0, 4.25))
```
```{r}
whole %>%
  filter(Гестация == 24) %>%
ggviolin (x = "name", y = "Сердце", fill = "name", palette = c("#CCFF99", "#FF99CC", "#CCCCFF", "#FFCC66", "#CC99FF", "#FFFF00", "#FF0000", "#FFCCCC"), alpha=0.5, size=0.1, width = 0.9,  add = "boxplot", add.params = list(fill = "white", size=0.2, width = 0.1, alpha=0.5))+
  theme_light()+
  xlab("Датафрейм")+
  ylab("Сердце, г")+
  ggtitle("Гестация - 24 неделя", )+
  theme(plot.title = element_text(hjust = 0.5 ))+
  theme(axis.title.y = element_text (size=12, margin = margin(l = 10, r = 10)))+
  theme(axis.title.x = element_text (size=12, margin = margin(t = 10, b = 10)))+
  theme(axis.text.x = element_text(size=10, ))+
  theme(legend.position = "none")+
  scale_x_discrete(labels=c('Исходный', 'Удаление
  пропусков', 'Замена NA
  на среднее', 'Замена NA
  на медиану','Замена NA
  на моду', 'knn5', 'MICE'))+
  scale_y_continuous (breaks = c (0,1,2,3,4,5,6,7,8,9,10), limits = c(0, 9))
```
```{r}
whole %>%
  filter(Гестация == 25) %>%
ggviolin (x = "name", y = "Лёгкие", fill = "name", palette = c("#CCFF99", "#FF99CC", "#CCCCFF", "#FFCC66", "#CC99FF", "#FFFF00", "#FF0000", "#FFCCCC"), alpha=0.5, size=0.1, width = 0.9,  add = "boxplot", add.params = list(fill = "white", size=0.2, width = 0.1, alpha=0.5))+
  theme_light()+
  xlab("Датафрейм")+
  ylab("Лёгкие, г")+
  ggtitle("Гестация - 25 неделя", )+
  theme(plot.title = element_text(hjust = 0.5 ))+
  theme(axis.title.y = element_text (size=12, margin = margin(l = 10, r = 10)))+
  theme(axis.title.x = element_text (size=12, margin = margin(t = 10, b = 10)))+
  theme(axis.text.x = element_text(size=10, ))+
  theme(legend.position = "none")+
  scale_x_discrete(labels=c('Исходный', 'Удаление
  пропусков', 'Замена NA
  на среднее', 'Замена NA
  на медиану','Замена NA
  на моду', 'knn5', 'MICE'))+
  scale_y_continuous (breaks = c (0,5,10,15,20,25,30,35,40,45,50), limits = c(0, 50))
```
```{r}
whole %>%
  filter(Гестация == 25) %>%
ggviolin (x = "name", y = "Поджелудочная железа", fill = "name", palette = c("#CCFF99", "#FF99CC", "#CCCCFF", "#FFCC66", "#CC99FF", "#FFFF00", "#FF0000", "#FFCCCC"), alpha=0.5, size=0.1, width = 1.5,  add = "boxplot", add.params = list(fill = "white", size=0.2, width = 0.1, alpha=0.5))+
  theme_light()+
  xlab("Датафрейм")+
  ylab("Поджелудочная железа, г")+
  ggtitle("Гестация - 25 неделя", )+
  theme(plot.title = element_text(hjust = 0.5 ))+
  theme(axis.title.y = element_text (size=12, margin = margin(l = 10, r = 10)))+
  theme(axis.title.x = element_text (size=12, margin = margin(t = 10, b = 10)))+
  theme(axis.text.x = element_text(size=10, ))+
  theme(legend.position = "none")+
  scale_x_discrete(labels=c('Исходный', 'Удаление
  пропусков', 'Замена NA
  на среднее', 'Замена NA
  на медиану','Замена NA
  на моду', 'knn5', 'MICE'))+
  scale_y_continuous (breaks = c (0,0.25,0.5,0.75,1,1.25,1.5,1.75,2,2.25,2.5,2.75,3), limits = c(0, 3))
```
```{r}
whole %>%
  filter(Гестация == 25) %>%
ggviolin (x = "name", y = "Селезёнка", fill = "name", palette = c("#CCFF99", "#FF99CC", "#CCCCFF", "#FFCC66", "#CC99FF", "#FFFF00", "#FF0000", "#FFCCCC"), alpha=0.5, size=0.1, width = 0.9,  add = "boxplot", add.params = list(fill = "white", size=0.2, width = 0.1, alpha=0.5))+
  theme_light()+
  xlab("Датафрейм")+
  ylab("Селезёнка, г")+
  ggtitle("Гестация - 25 неделя", )+
  theme(plot.title = element_text(hjust = 0.5 ))+
  theme(axis.title.y = element_text (size=12, margin = margin(l = 10, r = 10)))+
  theme(axis.title.x = element_text (size=12, margin = margin(t = 10, b = 10)))+
  theme(axis.text.x = element_text(size=10, ))+
  theme(legend.position = "none")+
  scale_x_discrete(labels=c('Исходный', 'Удаление
  пропусков', 'Замена NA
  на среднее', 'Замена NA
  на медиану','Замена NA
  на моду', 'knn5', 'MICE'))+
  scale_y_continuous (breaks = c (0,0.5,1, 1.5, 2,2.5,3,3.5,4,4.5), limits = c(0, 4.25))
```
```{r}
whole %>%
  filter(Гестация == 25) %>%
ggviolin (x = "name", y = "Сердце", fill = "name", palette = c("#CCFF99", "#FF99CC", "#CCCCFF", "#FFCC66", "#CC99FF", "#FFFF00", "#FF0000", "#FFCCCC"), alpha=0.5, size=0.1, width = 0.9,  add = "boxplot", add.params = list(fill = "white", size=0.2, width = 0.1, alpha=0.5))+
  theme_light()+
  xlab("Датафрейм")+
  ylab("Сердце, г")+
  ggtitle("Гестация - 25 неделя", )+
  theme(plot.title = element_text(hjust = 0.5 ))+
  theme(axis.title.y = element_text (size=12, margin = margin(l = 10, r = 10)))+
  theme(axis.title.x = element_text (size=12, margin = margin(t = 10, b = 10)))+
  theme(axis.text.x = element_text(size=10, ))+
  theme(legend.position = "none")+
  scale_x_discrete(labels=c('Исходный', 'Удаление
  пропусков', 'Замена NA
  на среднее', 'Замена NA
  на медиану','Замена NA
  на моду', 'knn5', 'MICE'))+
  scale_y_continuous (breaks = c (0,1,2,3,4,5,6,7,8,9,10), limits = c(0, 9.5))
```
```{r}
whole %>%
  filter(Гестация == 25) %>%
ggviolin (x = "name", y = "Тимус", fill = "name", palette = c("#CCFF99", "#FF99CC", "#CCCCFF", "#FFCC66", "#CC99FF", "#FFFF00", "#FF0000", "#FFCCCC"), alpha=0.5, size=0.1, width = 0.9,  add = "boxplot", add.params = list(fill = "white", size=0.2, width = 0.1, alpha=0.5))+
  theme_light()+
  xlab("Датафрейм")+
  ylab("Тимус, г")+
  ggtitle("Гестация - 25 неделя", )+
  theme(plot.title = element_text(hjust = 0.5 ))+
  theme(axis.title.y = element_text (size=12, margin = margin(l = 10, r = 10)))+
  theme(axis.title.x = element_text (size=12, margin = margin(t = 10, b = 10)))+
  theme(axis.text.x = element_text(size=10, ))+
  theme(legend.position = "none")+
  scale_x_discrete(labels=c('Исходный', 'Удаление
  пропусков', 'Замена NA
  на среднее', 'Замена NA
  на медиану','Замена NA
  на моду', 'knn5', 'MICE'))+
  scale_y_continuous (breaks = c (0,0.5,1, 1.5, 2,2.5,3,3.5,4,4.5,5.0,5.5,6.0), limits = c(0, 6))
```

